/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    retreats: Retreat;
    testimonials: Testimonial;
    'team-members': TeamMember;
    gallery: Gallery;
    videos: Video;
    inquiries: Inquiry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    retreats: RetreatsSelect<false> | RetreatsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    hero: Hero;
    about: About;
    'contact-info': ContactInfo;
    'seo-defaults': SeoDefault;
    cta: Cta;
    theme: Theme;
  };
  globalsSelect: {
    hero: HeroSelect<false> | HeroSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    'contact-info': ContactInfoSelect<false> | ContactInfoSelect<true>;
    'seo-defaults': SeoDefaultsSelect<false> | SeoDefaultsSelect<true>;
    cta: CtaSelect<false> | CtaSelect<true>;
    theme: ThemeSelect<false> | ThemeSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "retreats".
 */
export interface Retreat {
  id: string;
  title: string;
  /**
   * Photo gallery. The first image is used as the cover.
   */
  images: (string | Media)[];
  /**
   * e.g. "Khajuraho, India".
   */
  location: string;
  /**
   * Starting price per person (₹).
   */
  price: number;
  fromDate: string;
  toDate: string;
  /**
   * Out of 5.
   */
  ratings: number;
  /**
   * Main overview. Supports bold, italic, and bullet lists.
   */
  summary: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * What guests will experience day to day.
   */
  retreatExperience?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * What makes this retreat special.
   */
  specialities?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Food & dining details.
   */
  food?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * About the facilitator(s) / hosts.
   */
  facilitation?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Key benefits, one per tag. e.g. "Reduced stress", "Better sleep".
   */
  benefits?: string[] | null;
  /**
   * Add a day, then add timeline entries within it.
   */
  programItinerary?:
    | {
        /**
         * e.g. "Day 1 · Arrival & Grounding".
         */
        title?: string | null;
        timeline?:
          | {
              /**
               * e.g. "7:00 AM".
               */
              time: string;
              /**
               * What happens at this time.
               */
              description: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Select or type your own. Suggestions: Accommodation, All meals, Daily yoga, Airport transfer, Excursions, Welcome drink.
   */
  whatIncludes?: string[] | null;
  /**
   * Select or type your own. Suggestions: Flights, Travel insurance, Visa fees, Personal expenses, Spa treatments.
   */
  notIncluded?: string[] | null;
  /**
   * Select or type your own. Suggestions: Free Wifi, Swimming pool, Spa, Restaurant, Garden, Yoga shala, Parking.
   */
  availableFacilities?: string[] | null;
  accommodation?: {
    /**
     * Photo for the Shared option.
     */
    sharedImage?: (string | null) | Media;
    /**
     * Photo for the Private option.
     */
    privateImage?: (string | null) | Media;
    /**
     * Shared is priced at the retreat base price unless you override it.
     */
    sharedPriceMode?: ('base' | 'custom') | null;
    /**
     * Custom price per person for Shared (₹).
     */
    sharedPrice?: number | null;
    /**
     * Add-on added on top of the base price for Private (₹).
     */
    privateAddOn?: number | null;
  };
  /**
   * About the location and how to get there.
   */
  locationInformation?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  retreatReviews?:
    | {
        reviewerName: string;
        /**
         * Out of 5.
         */
        rating: number;
        reviewDescription: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Auto-generated from the title if left blank.
   */
  slug?: string | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Show on the landing page.
   */
  featured?: boolean | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  name: string;
  /**
   * e.g. "Yoga Student" or a short descriptor.
   */
  role?: string | null;
  quote: string;
  avatar?: (string | null) | Media;
  rating?: number | null;
  order?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * People shown in the "Meet your team" section on the home and about pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: string;
  name: string;
  /**
   * e.g. "Lead Yoga Teacher" or "Founder".
   */
  role?: string | null;
  /**
   * A portrait photo. A 4:5 (portrait) crop looks best.
   */
  image?: (string | null) | Media;
  /**
   * A short bio — one or two sentences.
   */
  about?: string | null;
  order?: number | null;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: string;
  image: string | Media;
  caption?: string | null;
  category?: ('Studio' | 'Retreats' | 'Events' | 'Nature' | 'Community') | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: string;
  title: string;
  videoType: 'embed' | 'upload';
  /**
   * Paste a YouTube/Vimeo URL.
   */
  embedUrl?: string | null;
  file?: (string | null) | Media;
  thumbnail?: (string | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: string;
  type: 'booking' | 'contact';
  status: 'new' | 'contacted' | 'archived';
  name: string;
  email: string;
  phone?: string | null;
  /**
   * Retreat of interest (booking inquiries).
   */
  service?: (string | null) | Retreat;
  /**
   * Free-text preferred date/time (Phase 1 — no calendar yet).
   */
  preferredDate?: string | null;
  /**
   * Chosen accommodation and total price at time of inquiry.
   */
  accommodation?: string | null;
  message?: string | null;
  /**
   * Was the admin notification email sent successfully?
   */
  notified?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'retreats';
        value: string | Retreat;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null)
    | ({
        relationTo: 'team-members';
        value: string | TeamMember;
      } | null)
    | ({
        relationTo: 'gallery';
        value: string | Gallery;
      } | null)
    | ({
        relationTo: 'videos';
        value: string | Video;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: string | Inquiry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "retreats_select".
 */
export interface RetreatsSelect<T extends boolean = true> {
  title?: T;
  images?: T;
  location?: T;
  price?: T;
  fromDate?: T;
  toDate?: T;
  ratings?: T;
  summary?: T;
  retreatExperience?: T;
  specialities?: T;
  food?: T;
  facilitation?: T;
  benefits?: T;
  programItinerary?:
    | T
    | {
        title?: T;
        timeline?:
          | T
          | {
              time?: T;
              description?: T;
              id?: T;
            };
        id?: T;
      };
  whatIncludes?: T;
  notIncluded?: T;
  availableFacilities?: T;
  accommodation?:
    | T
    | {
        sharedImage?: T;
        privateImage?: T;
        sharedPriceMode?: T;
        sharedPrice?: T;
        privateAddOn?: T;
      };
  locationInformation?: T;
  retreatReviews?:
    | T
    | {
        reviewerName?: T;
        rating?: T;
        reviewDescription?: T;
        id?: T;
      };
  slug?: T;
  order?: T;
  featured?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  quote?: T;
  avatar?: T;
  rating?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  image?: T;
  about?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  image?: T;
  caption?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  videoType?: T;
  embedUrl?: T;
  file?: T;
  thumbnail?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  type?: T;
  status?: T;
  name?: T;
  email?: T;
  phone?: T;
  service?: T;
  preferredDate?: T;
  accommodation?: T;
  message?: T;
  notified?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: string;
  /**
   * Small text above the headline, e.g. "Aumevya Yoga".
   */
  eyebrow?: string | null;
  /**
   * Main headline. Keep it short and evocative.
   */
  heading: string;
  /**
   * One or two supporting sentences.
   */
  subheading?: string | null;
  primaryCtaLabel?: string | null;
  primaryCtaHref?: string | null;
  secondaryCtaLabel?: string | null;
  secondaryCtaHref?: string | null;
  /**
   * Exactly 6 images shown floating in the hero. Order matters — they fill the layout clockwise from the top-left.
   */
  heroImages?: (string | Media)[] | null;
  /**
   * Tablet & mobile only. How visible the background hero images are (0 = hidden, 100 = full strength).
   */
  imageOpacity?: number | null;
  /**
   * Tablet & mobile only. Strength of the soft white wash behind the title & subtitle that keeps them legible.
   */
  overlayOpacity?: number | null;
  /**
   * Tablet & mobile only. How long each background image shows before turning to the next.
   */
  slideInterval?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: string;
  eyebrow?: string | null;
  heading: string;
  /**
   * Rich text — bold, links, lists. Layout stays developer-controlled.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (string | null) | Media;
  /**
   * Short stat cards, e.g. "10+ Years" / "Experience".
   */
  highlights?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info".
 */
export interface ContactInfo {
  id: string;
  email?: string | null;
  phone?: string | null;
  /**
   * WhatsApp number in international format, e.g. +91...
   */
  whatsapp?: string | null;
  address?: string | null;
  /**
   * Google Maps embed URL (src of the iframe).
   */
  mapEmbedUrl?: string | null;
  hours?:
    | {
        /**
         * e.g. Mon – Fri
         */
        days: string;
        /**
         * e.g. 6:00 AM – 9:00 PM
         */
        time: string;
        id?: string | null;
      }[]
    | null;
  socials?: {
    instagram?: string | null;
    facebook?: string | null;
    youtube?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults".
 */
export interface SeoDefault {
  id: string;
  siteName: string;
  /**
   * Use %s as a placeholder for the page title.
   */
  titleTemplate?: string | null;
  description: string;
  /**
   * Default social-share image (1200×630 recommended).
   */
  ogImage?: (string | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cta".
 */
export interface Cta {
  id: string;
  heading: string;
  subheading?: string | null;
  buttonLabel?: string | null;
  buttonHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme".
 */
export interface Theme {
  id: string;
  /**
   * Primary brand color. Drives buttons, links, gradients, focus rings and hover accents across the whole site. Default is Cromix Orange.
   */
  primaryColor: string;
  /**
   * Secondary accent. Used for star ratings, small badges and the highlight in gradients.
   */
  accentColor: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  subheading?: T;
  primaryCtaLabel?: T;
  primaryCtaHref?: T;
  secondaryCtaLabel?: T;
  secondaryCtaHref?: T;
  heroImages?: T;
  imageOpacity?: T;
  overlayOpacity?: T;
  slideInterval?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  body?: T;
  image?: T;
  highlights?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-info_select".
 */
export interface ContactInfoSelect<T extends boolean = true> {
  email?: T;
  phone?: T;
  whatsapp?: T;
  address?: T;
  mapEmbedUrl?: T;
  hours?:
    | T
    | {
        days?: T;
        time?: T;
        id?: T;
      };
  socials?:
    | T
    | {
        instagram?: T;
        facebook?: T;
        youtube?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults_select".
 */
export interface SeoDefaultsSelect<T extends boolean = true> {
  siteName?: T;
  titleTemplate?: T;
  description?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cta_select".
 */
export interface CtaSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  buttonLabel?: T;
  buttonHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme_select".
 */
export interface ThemeSelect<T extends boolean = true> {
  primaryColor?: T;
  accentColor?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}